---
- name: Create Pikachu User Across Linux and VyOS 1.4.3
  hosts: linux_hosts
  gather_facts: yes
  
  tasks:
    # --- SECTION 1: LINUX HOSTS (Ubuntu, Fedora, Oracle) ---
    - name: Create Pikachu user on Linux distributions
      ansible.builtin.user:
        name: Pikachu
        # Password 'changeme' hashed for Linux security
        password: "{{ 'changeme' | password_hash('sha512') }}"
        shell: /bin/bash
        # Dynamic group selection: 'wheel' for RedHat/Oracle, 'sudo' for others
        groups: "{{ 'wheel' if ansible_os_family in ['RedHat', 'Oracle Linux'] else 'sudo' }}"
        append: yes
        state: present
      become: yes
      # Only runs if the host is NOT a network device
      when: ansible_network_os is not defined

    # --- SECTION 2: VyOS 1.4.3 (Sagitta Syntax) ---
    - name: Configure Pikachu user on VyOS
      vyos.vyos.vyos_config:
        lines:
          - set system login user Pikachu full-name "Pikachu Admin"
          - set system login user Pikachu authentication plaintext-password "changeme"
          # VyOS 1.4+ uses 'role admin' instead of 'level 15'
          - set system login user Pikachu role admin
      # Only runs if the host is specifically in the vyos group
      when: "'vyos' in group_names"